server:
  port: 8032
spring:
  rabbitmq:
    host: 130.1.1.45
    port: 5672
    username: guest #http://localhost:15672/
    password: guest
    
rabbitmq:
  queue:
    name: sample-queue
  exchange:
    name: sample-exchange
  routing:
    key : key